# Generated by Django 5.1.5 on 2025-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_author_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое содержание'),
        ),
    ]
