# Generated by Django 5.1.5 on 2025-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
