# Generated by Django 5.1.5 on 2025-02-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_author_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(unique=True, verbose_name='ISBN'),
        ),
    ]
